# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 09:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default=b'', max_length=100)),
                ('pin_code', models.CharField(blank=True, default=b'', max_length=6, validators=[django.core.validators.RegexValidator(message=b'Enter pin code.', regex=b'^\\+?1?\\d{6}$')])),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
