# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='logged_in',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
    ]
