# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 09:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resend_otp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message=b"Enter country code. Phone number must be entered in the format: '+919999999'.", regex=b'^\\+?1?\\d{12}$')])),
            ],
        ),
    ]
