# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_otp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generate_otp',
            name='file_no',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
    ]
